### ISSUE TITLE
Logout Button doesn't do anything

### ISSUE THREAD

**Issue by LokmanChu** [hassib291/taskScheduler#13]
Probably best solution is Mainscreen.close and call LoginDialog.show

**Comment by hassib-ashouri** [comment]
should we make save before logging out?

**Comment by LokmanChu** [comment]
Should it prompt a save? or automatically do so

**Comment by LokmanChu** [comment]
You can also make a 
Save before logging out?
Yes No Dialog

**Comment by LokmanChu** [comment]
Look at CreateEditProjectDialog's deleteStatus method to get an idea on how to do this
