### ISSUE TITLE
+ Buttons on top of Categories can't create new Task with Status

### ISSUE THREAD

**Issue by LokmanChu** [hassib291/taskScheduler#5]
Currently, it is impossible to have the CreateEditTaskDialog know which Category + Task button is being pressed.

Potential Solutions: 
- Ignore the issue. Default all new Tasks to topStatus
- Instead of passing null to the Dialog, pass a new TaskModel with status set to the status added to.

**Comment by hassib-ashouri** [comment]
logic is not is not implemented yet.

**Comment by hassib-ashouri** [comment]
can u implement the constructor where it takes the the String for the status in the constructor.
Because if I passed an empty task, the code will thing its editing.
